### ISSUE TITLE
[feat] Implement OP_DEPTH opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#10]
Implement the OP_DEPTH opcode using the opcodeDepth reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1295)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by okhaimie-dev** [comment]
Can I attempt this?

**Comment by b-j-roberts** [comment]
Definitely @okhaimie-dev , lmk if you have any questions!

**Comment by okhaimie-dev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
contributor to cairobook, and i am currently building a game with dojo framework

### How I plan on tackling this issue
i read the contributor guide, and i'll reference btcd example
