### ISSUE TITLE
[feat] Request to implement OP_EQUALVERIFY

### ISSUE THREAD

**Issue by varun-doshi** [keep-starknet-strange/shinigami#100]
#### References
Would like to implement `OP_EQUALVERIFY` 

Apologies for not waiting for the official issue. 
This PR can be clubbed with other similar OPCODES.

**Comment by PavitraAgarwal21** [comment]
i can implement this , can you assign to me ?

**Comment by ShantelPeters** [comment]
@varun-doshi can I work on this ?

**Comment by b-j-roberts** [comment]
This opcode was grouped in with another PR, so it has been added. Thank you for setting up the issue!
