### ISSUE TITLE
[bug] disabled, unimplemented, and unknown opcodes should throw an error regardless of IF conditions

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [keep-starknet-strange/shinigami#109]
**How to reproduce:**
While developing the disabled opcodes feature I noticed that I can still use a disabled opcode if it is an IF block that is never executed. 
For example this script: `OP_0 OP_IF OP_MUL OP_ELSE OP_DROP OP_ENDIF`

The same is probably true of unkown opcodes as well. However this is not emulating bitcoin mainnet consensus rules. The interperter in bitcoin core will first check for disabled or unknown opcodes and throw before executing the current opcode.

https://github.com/bitcoin/bitcoin/blob/master/src/script/interpreter.cpp#L456

**Comment by adrianvrj** [comment]
Hi, is this open for contributions?
If so, can I work on this?

**Comment by ShantelPeters** [comment]
Hello @0xBEEFCAF3 is this issue open for contribution? If yes, can I be assigned to it please

**Comment by ShantelPeters** [comment]
I am applying for this issue via https://app.onlydust.com/p/shinigami

Please can I take this up ?

**Comment by b-j-roberts** [comment]
@adrianvrj would you still be interested in working on this? I'll assign you, but lmk if not.

We have been following the design of btcd pretty closely, so these links might help:
- [isOpcodeDisabled check in the engine](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/engine.go#L462)
- [engine execution in Shinigami](https://github.com/keep-starknet-strange/shinigami/blob/72d05da014ecd9929a90d344668df0a842ac5b71/src/engine.cairo#L95)
- [tests that should pass after fixing this bug](https://github.com/keep-starknet-strange/shinigami/blob/53ab9c10d70df7667ebab14903c19dabd325d367/src/opcodes/tests/test_disabled.cairo#L77)

**Comment by adrianvrj** [comment]
@b-j-roberts I will take care of this one, ty very much
