### ISSUE TITLE
[feat] Implement OP_SUB opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#11]
Implement the OP_SUB opcode using the opcodeSub reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1555)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by TAdev0** [comment]
hi @b-j-roberts  , may i be assigned to this issue? :)

**Comment by b-j-roberts** [comment]
For sure, @TAdev0 . Glad to have you on the project!
