### ISSUE TITLE
[feat] Implement OP_VERIF & OP_NOTVERIF opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#112]
Implement the OP_VERIF & OP_NOTVERIF opcodes using [opcodeReserved](https://github.com/keep-starknet-strange/shinigami/blob/53ab9c10d70df7667ebab14903c19dabd325d367/src/opcodes/utils.cairo#L17)

This work will involve adding something like [isOpcodeAlwaysIllegal](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/engine.go#L468) from btcd to the [Shinigami engine](https://github.com/keep-starknet-strange/shinigami/blob/main/src/engine.cairo).

#### References

Note: This link isn't fully up to date on adding opcodes, but should be a good start:
[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by EjembiEmmanuel** [comment]
@b-j-roberts I

**Comment by ShantelPeters** [comment]
Hey @b-j-roberts can I jump on this ?

**Comment by b-j-roberts** [comment]
Hey @mexes20 , I'll assign you. Let me know if you have questions.

**Comment by b-j-roberts** [comment]
@mexes20 any updates on this issue?

**Comment by adrianvrj** [comment]
Hey @b-j-roberts if there is no response from the assigned dev, can I work on this?

**Comment by b-j-roberts** [comment]
> Hey @b-j-roberts if there is no response from the assigned dev, can I work on this?

Yes, feel free to work on the issue if you're available.
