### ISSUE TITLE
[feat] Implement OP_NOP1, OP_NOP4-OP_NOP10 opcodes

### ISSUE THREAD

**Issue by manlikeHB** [keep-starknet-strange/shinigami#113]
Implement the OP_NOP1, OP_NOP4-OP_NOP10 opcode using the OP_NOP1, OP_NOP4-OP_NOP10 [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L820)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Jemiiah** [comment]
I would love to work on this issue

**Comment by b-j-roberts** [comment]
Thanks for creating this issue @manlikeHB, lmk if you have any questions.
