### ISSUE TITLE
[dev] Upgrade Shinigami to Cairo 2.7.0

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#114]
Cairo and scarb 2.7.0 have released, and we will need to upgrade in order to take advantage of some of the changes. Including the integration of `sha256` hashing.

https://community.starknet.io/t/cairo-v2-7-0-is-coming/114362

The scarb version will need to be changed in [tool-versions](https://github.com/keep-starknet-strange/shinigami/blob/main/.tool-versions), and if there are any breaking changes they will need to be resolved.

**Comment by supreme2580** [comment]
Hi @b-j-roberts  can I be assigned to this?

**Comment by okhaimie-dev** [comment]
hehe, can I claim this.

**Comment by raizo07** [comment]
@b-j-roberts can I work on this?

**Comment by ShantelPeters** [comment]
Hello @b-j-roberts can I work on this issue ?

**Comment by b-j-roberts** [comment]
@supreme2580 Thanks for showing interest. I'll assign you, let me know if you run into any issues.

**Comment by Gift-Naomi** [comment]
@b-j-roberts can I work on this?

**Comment by supreme2580** [comment]
Thank you @b-j-roberts
