### ISSUE TITLE
[feat] Implement OP_DATA_X opcodes,  OP_DATA_7 - OP_DATA_75

### ISSUE THREAD

**Issue by Shoetan** [keep-starknet-strange/shinigami#116]
Implement `OP_DATA_X` opcodes,  `OP_DATA_7` - `OP_DATA_75` [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L320)

#### References
[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Shoetan** [comment]
@b-j-roberts Kindly assign. Thank you.

**Comment by b-j-roberts** [comment]
Thank you, lmk if you have any issues.
