### ISSUE TITLE
[feat] Implement OP_NIP

### ISSUE THREAD

**Issue by varun-doshi** [keep-starknet-strange/shinigami#118]
Implement the `OP_NIP`

**Comment by varun-doshi** [comment]
@b-j-roberts  I would like to take this up. Kindly assign

Thank you

**Comment by b-j-roberts** [comment]
`OP_NIP` has already been implemented https://github.com/keep-starknet-strange/shinigami/blob/53ab9c10d70df7667ebab14903c19dabd325d367/src/opcodes/opcodes.cairo#L48
