### ISSUE TITLE
[feat] Implement OP_LESSTHAN opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#13]
#### References
Implement the OP_LESSTHAN opcode using the opcodeLessThan reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1695)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by TAdev0** [comment]
Hi @b-j-roberts  can I be assign to a second one, this one for example?

**Comment by TAdev0** [comment]
@b-j-roberts  up

**Comment by manoahLinks** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
Aside me being a rustacean, i have experience with how a compiler works

### How I plan on tackling this issue
i will create a function that treats the top 2 items on the data stack as integers and check if the second item is less than the first then they are replace with a 1 else 0

**Comment by prasincs** [comment]
@b-j-roberts I can take this one?

**Comment by AbdelStark** [comment]
> @b-j-roberts I can take this one?

Yes please do. Assigned to you
