### ISSUE TITLE
[bug] [bitcoin-core test] ''' DUP HASH256 SWAP SHA256 SHA256 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#130]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
'' DUP HASH256 SWAP SHA256 SHA256 EQUAL
```

This is possibly due to some kind of overflow with `i64` while hashing

We expect this test to pass and execute successfully.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],10023,2,[120734409039858093552956132617158781462505867478866172029331723693562607136],297717285196,5]'
```

**Comment by adrianvrj** [comment]
hey can I work on this?

**Comment by b-j-roberts** [comment]
For sure @adrianvrj , thank you!

**Comment by b-j-roberts** [comment]
Duplicate bug from this issue: https://github.com/keep-starknet-strange/shinigami/issues/145
