### ISSUE TITLE
[bug] [bitcoin-core test] '0 IF 0x01 0x81 ENDIF 1 '

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#131]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
0 IF 0x01 0x81 ENDIF 1
```

We expect this test to pass and execute successfully.
More info from the test: `1NEGATE equiv`

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],18006118492099244450712950776978963358421403790876721,22,[],0,0]'
```

**Comment by jsandinoDev** [comment]
Hi can I work on this ? @b-j-roberts

**Comment by b-j-roberts** [comment]
Definitely @jsandinoDev , Let me know if you have any questions or issues!
