### ISSUE TITLE
[bug] [bitcoin-core test] '0x4d0200ff 0x01 NOP'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#132]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
0x4d0200ff 0x01 NOP
```

We expect this test to fail with an error, but it is running fine.
More info from the test: `PUSHDATA2 with not enough bytes`

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],228890975661967874745958,10,[],3492594498579353424,8]'
```

**Comment by EmmanuelAR** [comment]
Heyyy can I work on this ? @b-j-roberts

**Comment by b-j-roberts** [comment]
@EmmanuelAR Definitely, thank you!

**Comment by bloomingpeach** [comment]
@EmmanuelAR, It appears that the code in your pull request is identical to mine, including the comments, I kindly request that you acknowledge this in your PR. Thanks!
