### ISSUE TITLE
[bug] [bitcoin-core test] '0x4e03000000ffff 0x01 NOP'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#133]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
0x4e03000000ffff 0x01 NOP
```

We expect this test to fail with an error, but it is running fine.
More info from the test: `PUSHDATA4 with not enough bytes`

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],64427082122961108293098671622834251366,16,[],3492594498579353424,8]'
```

**Comment by EmmanuelAR** [comment]
Heyyy can work on this ? @b-j-roberts i already work on art peace

**Comment by EmmanuelAR** [comment]
Heyyy can work on this ? @b-j-roberts i already work on art peace

**Comment by b-j-roberts** [comment]
@EmmanuelAR  I'll keep this one open for now while you work on the other one.

**Comment by EmmanuelAR** [comment]
Got it @b-j-roberts

**Comment by diegoTech14** [comment]
Hello! @b-j-roberts can I help with this issue?

**Comment by martinvibes** [comment]
hello @b-j-roberts i would love to help in solving this issue and  to be a contrbutor to your repo

**Comment by manlikeHB** [comment]
@b-j-roberts can i work on this?

**Comment by stevencartavia** [comment]
Hi, can I work on this?

**Comment by b-j-roberts** [comment]
@diegoTech14 for sure, thank you for the help. Let me know if you have any issues.

**Comment by diegoTech14** [comment]
Thank you sir, I'll start to work! @b-j-roberts
