### ISSUE TITLE
[bug] [bitcoin-core test] '0 NOTIF 123'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#134]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
0 NOTIF 123
```

We expect this to fail with an `UNBALANCED_CONDITIONAL` error do to missing ending.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],13546319592573254,7,[],3224115,3]'
```

**Comment by addegbenga** [comment]
Can I work on this

**Comment by b-j-roberts** [comment]
Hey @addegbenga , thanks! I'll assign you now.

**Comment by b-j-roberts** [comment]
This issue was solved in another PR which separated the scriptsig and pub key. https://github.com/keep-starknet-strange/shinigami/pull/152
