### ISSUE TITLE
[bug] [bitcoin-core test] 'NOP OVER 1'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#135]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
NOP OVER 1
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],5132112,3,[],87231948791857,6]'
```

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue

**Comment by b-j-roberts** [comment]
@ShantelPeters For sure, thank you! Let me know if you have any issues.

**Comment by ShantelPeters** [comment]
@b-j-roberts Thank you sir … 
I’ll get to work immediately.
