### ISSUE TITLE
[bug] [bitcoin-core test] '1 OVER'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#136]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
1 OVER
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

More info from the test:

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],49,1,[],1331053906,4]'
```

**Comment by Gerson2102** [comment]
Maybe not a good first issue but I would like to try it!

**Comment by b-j-roberts** [comment]
@Gerson2102 No worries at all, let me know if you run into any questions or issues. Thank you!

**Comment by bloomingpeach** [comment]
Hi @b-j-roberts, can I work on this issue?

**Comment by Gerson2102** [comment]
@b-j-roberts hey mate, i have not been working on this issue cause ive been working on other issues, sorry for the inconveniencies.

**Comment by b-j-roberts** [comment]
Okay, I will say @bloomingpeach you can work on this if you'd like then. Thanks for the update @Gerson2102

**Comment by b-j-roberts** [comment]
Seems this was a duplicate bug to another issue which was resolved by [this PR](https://github.com/keep-starknet-strange/shinigami/pull/161), so I'll close this issue.
