### ISSUE TITLE
[bug] [bitcoin-core test] '1 -1 PICK'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#137]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
1 -1 PICK
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],49,1,[],12720388807672651,7]'
```

**Comment by od-hunter** [comment]
Can I fix this please @b-j-roberts

**Comment by mubarak23** [comment]
@b-j-roberts can I work on this

**Comment by b-j-roberts** [comment]
For sure @mubarak23 , I'll assign you since @od-hunter will be working on #140 .

Let me know if you have questions. Thanks

**Comment by mubarak23** [comment]
the bug is happening from this function 

```
  fn pick_n(ref self: ScriptStack, idx: i32) -> Result<(), felt252> {
        println!("Before running the operation");
         println!("IDX is {:?}", idx);

         let so = self.peek_byte_array(idx.try_into().unwrap())?;
        // let so = self.peek_byte_array(idx)?;
        println!(" result of pick_n  {:?}", so);
        self.push_byte_array(so);
        return Result::Ok(());
    }
```

this line 
`let so = self.peek_byte_array(idx.try_into().unwrap())?;`

trying to convert idx of type i32 into u32

error return 
`
Run panicked with [29721761890975875353235833581453094220424382983267374 ('Option::unwrap failed.'), ].`

@b-j-roberts
