### ISSUE TITLE
[bug] [bitcoin-core test] 'NOP 2DUP 1'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#138]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
NOP 2DUP 1
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],5132112,3,[],55269070479409,6]'
```

**Comment by EmmanuelAR** [comment]
Heyyyy @b-j-roberts fan I work o this ???? I already work with u !

**Comment by b-j-roberts** [comment]
Hey @EmmanuelAR , I'll keep this open while you work on the other issue for now. Thanks

**Comment by coxmars** [comment]
Hi @b-j-roberts this is not a good first issue but I would like to try it if you want 🫡

**Comment by manoahLinks** [comment]
Hi @b-j-roberts i would love to work on this

**Comment by manlikeHB** [comment]
@b-j-roberts, can i work on this?

**Comment by b-j-roberts** [comment]
This seems to have been a duplicate bug and has been resolved from this PR : https://github.com/keep-starknet-strange/shinigami/pull/155
