### ISSUE TITLE
[bug] [bitcoin-core test] '1 2DUP 1'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#139]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
1 2DUP 1
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],49,1,[],55269070479409,6]'
```

**Comment by adrianvrj** [comment]
Hi @b-j-roberts can I work on this?

**Comment by b-j-roberts** [comment]
@adrianvrj I'll keep this one open for now while you are on the other issue. Thanks.

**Comment by raizo07** [comment]
@b-j-roberts Can I work on this?

**Comment by b-j-roberts** [comment]
Yeah, I'll assign you. Thanks @raizo07

**Comment by b-j-roberts** [comment]
This seems to have been a duplicate bug and was resolved as part of this PR : https://github.com/keep-starknet-strange/shinigami/pull/155

**Comment by raizo07** [comment]
> This seems to have been a duplicate bug and was resolved as part of this PR : #155

Been working on this, I was already going to send a PR for it @b-j-roberts
