### ISSUE TITLE
[feat] Implement OP_GREATERTHAN opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#14]
Implement the OP_GREATERTHAN opcode using the opcodeGreaterThan reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1720)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by supreme2580** [comment]
Hi @b-j-roberts can I be assigned to this?

**Comment by b-j-roberts** [comment]
Thanks for the PR! I'll review soon @supreme2580
