### ISSUE TITLE
[bug] [bitcoin-core test] 'NOP 3DUP 1'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#140]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
NOP 3DUP 1
```

This code should be failing due to a `INVALID_STACK_OPERATION`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],5132112,3,[],56368582107185,6]'
```

**Comment by od-hunter** [comment]
Hi @b-j-roberts Can I work on this please?

**Comment by b-j-roberts** [comment]
@od-hunter Hey, welcome! Definitely, I'll assign you.

**Comment by od-hunter** [comment]
[Demo](https://github.com/od-hunter/shinigami/tree/fix_bug_with_nop_3_dup_1)
