### ISSUE TITLE
[bug] [bitcoin-core test] '-2147483648 0 ADD NOP'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#141]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
-2147483648 0 ADD NOP
```

This code should be failing due to an error.
More info from the test: `arithmetic operands must be in range [-2^31...2^31]

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],15379423392836554346419432256685136233540,17,[],5132112,3]'
```

**Comment by jsandinoDev** [comment]
Hi can I work on this ? @b-j-roberts

**Comment by b-j-roberts** [comment]
@jsandinoDev I'll keep this issue open for now while you are on the other issue. Thank you for the interest.

**Comment by chachaleo** [comment]
Hey, can I work on this ? :)

**Comment by b-j-roberts** [comment]
For sure @chachaleo , let me know if you have any questions!
