### ISSUE TITLE
[bug] [bitcoin-core test] '2147483647 DUP ADD 4294967294 NUMEQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#142]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
2147483647 DUP ADD 4294967294 NUMEQUAL
```

This code should be failing due to an error.
More info from the test: `NUMEQUAL must be in numeric range`

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],4372357539058384277836571663884584193442884,18,[],1164013830132011234147657419853840811581325644,19]'
```

**Comment by Oshioke-Salaki** [comment]
Please can I fix this bug?

**Comment by b-j-roberts** [comment]
@Oshioke-Salaki sure, I'll assign you for this one. Thank you
