### ISSUE TITLE
Bug: [bitcoin-core test] '0x4c01 0x01 NOP'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#144]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
0x4c01 0x01 NOP
```

We expect this test to fail with an error, but it is running fine.
More info from the test: `PUSHDATA1 with not enough bytes`

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],53292833124401,6,[],3492594498579353424,8]'
```

**Comment by b-j-roberts** [comment]
@manoahLinks thanks for showing interest in helping with these tests. Could you comment here and I can assign you?

**Comment by manoahLinks** [comment]
thanks brandon, i will be glad to work on this

**Comment by b-j-roberts** [comment]
This bug was resolved as part of another PR so I will close it.

https://github.com/keep-starknet-strange/shinigami/pull/154
