### ISSUE TITLE
[bug] [bitcoin-core test] ''' DUP HASH160 SWAP SHA256 RIPEMD160 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#145]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
'' DUP HASH160 SWAP SHA256 RIPEMD160 EQUAL
```

This is possibly due to some kind of overflow with `i64` while hashing

We expect this test to pass and execute successfully.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],10023,2,[120734409039858093552860717021263996134588021710877456776110186170841646129],3904656359019594060,8]'
```

**Comment by b-j-roberts** [comment]
@supreme2580 thank you for showing interest in helping with these bitcoin-core tests, could you comment here and I can assign you?

**Comment by supreme2580** [comment]
Hi

**Comment by supreme2580** [comment]
> @supreme2580 thank you for showing interest in helping with these bitcoin-core tests, could you comment here and I can assign you?

Yes sirrrr
