### ISSUE TITLE
[bug] [bitcoin-core test] '2147483648 0 ADD NOP'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#146]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
2147483648 0 ADD NOP
```

This code should be failing due to an error.
More info from the test: `arithmetic operands must be in range [-2^31...2^31]

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],66716881394323490567574922255566718020,16,[],5132112,3]'
```

**Comment by b-j-roberts** [comment]
@varun-doshi thank you for showing interest in these bitcoin-core test issues. Could you comment here and I can assign you to this task? Appreciate it!

**Comment by varun-doshi** [comment]
Hey @b-j-roberts 
I'm ready to take this up. Please assign it to me

Thank you

**Comment by b-j-roberts** [comment]
This ended up being a duplicate to https://github.com/keep-starknet-strange/shinigami/issues/142 so I will close it.
