### ISSUE TITLE
[feat] Implement OP_LESSTHANOREQUAL opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#15]
Implement the OP_LESSTHANOREQUAL opcode using the opcodeLessThanOrEqual reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1744)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by okhaimie-dev** [comment]
@b-j-roberts I'll like to work on this next. Maybe, I'll wait on the other PR reviews first

**Comment by okhaimie-dev** [comment]
@b-j-roberts I have fixed your suggestions in my other PRs, can I get started on this?

**Comment by okhaimie-dev** [comment]
completed this, but waiting on this PR to merge
https://github.com/keep-starknet-strange/shinigami/pull/32

i need an implement of at least OP_2 & OP_3 to test
