### ISSUE TITLE
Shinigami Frontend Figma design

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#157]
Create a design for the shinigami frontend. https://www.shinigamibtc.dev

**Comment by b-j-roberts** [comment]
@israelrex9 Thank you for helping on this issue!

**Comment by ooochoche** [comment]
Hi

**Comment by Israelrex9** [comment]
Thank you @b-j-roberts 
here is the figma design dev link

https://www.figma.com/design/Hp700m5HMG67nBJZ8T6l9r/Bitcoin-Wildlife?node-id=1457-10956&m=dev

**Comment by martinvibes** [comment]
hello @Israelrex9 I'm a frontend dev and i would love to participate on this issue as this will be my first time
