### ISSUE TITLE
[feat] Implement OP_GREATERTHANOREQUAL opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#16]
Implement the OP_GREATERTHANOREQUAL opcode using the opcode1Negate reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1768)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by nehkee** [comment]
I would like to work on this . Can you assign it to me ? I'll work on it asap

**Comment by okhaimie-dev** [comment]
@nehkee let me know if you need help with this.

cc: @b-j-roberts i am happy to make a PR for this just in-case nehkee wants me to handle it. I already complete this implementation on my localhost

**Comment by b-j-roberts** [comment]
@okhaimie-dev Feel free to create the PR, it seems @nehkee hasn't been able to start yet. I'll assign @nehkee a new issue when they become available!
