### ISSUE TITLE
[feat] Monaco editor font

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#166]
Change the font on our monaco editors to be Jura font.

`import { Jura } from "next/font/google";`
[font](https://fonts.google.com/specimen/Jura)
[script editor](https://github.com/keep-starknet-strange/shinigami/blob/main/frontend/src/components/script-editor.tsx)

**Comment by EjembiEmmanuel** [comment]
D

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts can I work on this please ?

**Comment by ShantelPeters** [comment]
let me work on this

**Comment by martinvibes** [comment]
hi @b-j-roberts please let me work on this, this will be my first time on your repo

**Comment by Kaminar-i** [comment]
please let me work on this @b-j-roberts

**Comment by b-j-roberts** [comment]
@martinvibes I'll assign you, thank you and welcome to the project! Let me know if you have questions!

**Comment by martinvibes** [comment]
thank you @b-j-roberts i'll get to work
