### ISSUE TITLE
[feat] Implement OP_MIN opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#17]
Implement the OP_MIN opcode using the opcodeMin reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1792)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by ptisserand** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
I'm a cairo developer  and I'm interested in learning more about Bitcoin script VM

### How I plan on tackling this issue
I will look at btcsuite implementation and implement this opcode in cairo with associated tests

**Comment by b-j-roberts** [comment]
Glad to have you on the project @ptisserand !
