### ISSUE TITLE
[feat] Script Flags: ScriptDiscourageUpgradableNops

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#174]
Bitcoin supports various script flags to enable/disable certain features. The `ScriptDiscourageUpgradableNops` script flag is used to cause a script to throw an error if an upgradable NOP opcode is used.

This issue will be to implement this flag into the Shinigami engine and create a set of test cases to verify the logic works as expected.

I recommend following the btcd implementation of ScriptDiscourageUpgradableNops for reference, since our designs are so similar.

#### References
[Shinigami scriptflags](https://github.com/keep-starknet-strange/shinigami/blob/ab4d20ad1824ed9b594d4d54464c6bc117410a70/src/scriptflags.cairo#L8C5-L8C35)
[btcd ScriptDiscourageUpgradableNops](https://github.com/search?q=repo%3Abtcsuite%2Fbtcd%20ScriptDiscourageUpgradableNops&type=code)
[Shinigami opcodes](https://github.com/keep-starknet-strange/shinigami/tree/main/src/opcodes)

**Comment by b-j-roberts** [comment]
@manny-uncharted thank you for looking into this! Please comment here.

**Comment by ScottyDavies** [comment]
Hello @b-j-roberts can you please assign this issue to me?

**Comment by manny-uncharted** [comment]
@b-j-roberts I'd take this on

**Comment by b-j-roberts** [comment]
@manny-uncharted Have you had to chance to work on this script flag?

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts can i please work on this?
