### ISSUE TITLE
[feat] Script flags: Minimal data

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#175]
Bitcoin supports various script flags to enable/disable certain features. The `ScriptVerifyMinimalData` flag is used to require transactions have the minimal amount of data in push operation.

This issue will be to implement this flag into the Shinigami engine and create a set of test cases to verify the logic works as expected.

I recommend following the btcd implementation of ScriptVerifyMinimalData for reference, since our designs are so similar.

#### References
[Shinigami scriptflags](https://github.com/keep-starknet-strange/shinigami/blob/ab4d20ad1824ed9b594d4d54464c6bc117410a70/src/scriptflags.cairo#L20)
[btcd ScriptVerifyMinimalData](https://github.com/search?q=repo%3Abtcsuite%2Fbtcd+ScriptVerifyMinimalData&type=code)
[Shinigami engine](https://github.com/keep-starknet-strange/shinigami/tree/main/src/engine.cairo)

**Comment by b-j-roberts** [comment]
@ooochoche Would you be interested in taking this issue? Please comment here if so, thank you!

**Comment by Gift-Naomi** [comment]
@b-j-roberts Can i work on this?

**Comment by ooochoche** [comment]
Yes I am interested @b-j-roberts thank you

**Comment by b-j-roberts** [comment]
@ooochoche Have you been able to work on this script flag?

**Comment by ooochoche** [comment]
I will create a PR today @b-j-roberts
