### ISSUE TITLE
[feat] Max Stack Size

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#176]
Bitcoin Script has a max stack size of 1000 items. We will need to implement checks into the engine to ensure this stack size is never exceeded.

I'd recommend following the design of btcd for stack size, since our engine design is so similar.

#### References
[btcd stack size](https://github.com/search?q=repo%3Abtcsuite%2Fbtcd%20MaxStackSize&type=code)
[Shinigami engine](https://github.com/keep-starknet-strange/shinigami/blob/main/src/engine.cairo)

**Comment by b-j-roberts** [comment]
@mubarak23 Please comment here if you'd like to take on this issue. thank you!

**Comment by mubarak23** [comment]
am here , yes
