### ISSUE TITLE
[feat] Implement OP_MAX opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#18]
Implement the OP_MAX opcode using the opcodeMax reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1816)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by lomasson** [comment]
Hi, can i have this one ?

**Comment by b-j-roberts** [comment]
For sure, let me know if you have questions!
