### ISSUE TITLE
[feat] P2PK transaction support

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#183]
Currently, all the opcodes for P2PK are implemented. To ensure we support all P2PK transactions/formats, we will need to create a set of tests for these transaction types and ensure all the logic and edge cases are handled properly. Also, including a P2PK transaction from mainnet as a test would be ideal.

#### References
[learn P2PK & examples](https://learnmeabitcoin.com/technical/script/p2pk/)
[example crypto tests](https://github.com/keep-starknet-strange/shinigami/blob/main/src/opcodes/tests/test_crypto.cairo)

**Comment by b-j-roberts** [comment]
@ptisserand Thank you for looking into this!

**Comment by ptisserand** [comment]
@b-j-roberts could you please assign to me ?

**Comment by mubarak23** [comment]
@b-j-roberts let work on this since it is related to my previous issue

**Comment by ScottyDavies** [comment]
@b-j-roberts can I please be assigned this task?

**Comment by bloomingpeach** [comment]
Hi seems @ptisserand is quite busy working on other projects, could I have a chance to work on this @b-j-roberts if it's okay. Thanks!

**Comment by b-j-roberts** [comment]
@bloomingpeach Sure, feel free to take a look. Thank you!

Some changes have been made since creating this issue, I'd recommend looking at this P2PK test for direction. Feel free to let me know if it isn't fully clear. https://github.com/keep-starknet-strange/shinigami/blob/6496bc124167658168f9e2835b58534967240ff3/src/tests/test_transactions.cairo#L73
I'd recommend creating test cases from all the transactions mentioned in the [learnmebitcoin](https://learnmeabitcoin.com/technical/script/p2pk/) article and a couple other random ones from mainnet. ( if / when you have time )

**Comment by bloomingpeach** [comment]
Hi @b-j-roberts where could i learn more about the `utxo_hints`(https://github.com/keep-starknet-strange/shinigami/blob/6496bc124167658168f9e2835b58534967240ff3/src/tests/test_transactions.cairo#L80C5-L87C39), I don't quite see the term anywhere.

**Comment by b-j-roberts** [comment]
> Hi @b-j-roberts where could i learn more about the `utxo_hints`(https://github.com/keep-starknet-strange/shinigami/blob/6496bc124167658168f9e2835b58534967240ff3/src/tests/test_transactions.cairo#L80C5-L87C39), I don't quite see the term anywhere.

So the `utxo_hint` term is just a term I coined, so probably wont be info anywhere. But essentially, the utxo_hints contain all the [old valid transaction utxos that will be used to process that transaction](https://github.com/keep-starknet-strange/shinigami/blob/688e464c6bb394608a37dcc1cf0a9f8db2ee9f5f/src/tests/test_transactions.cairo#L81). 
So for the example in the linked test, you can see the [transaction has one input.](https://learnmeabitcoin.com/explorer/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16)
![image](https://github.com/user-attachments/assets/1447425e-be4e-4f97-88b9-3809f4cf3242)

That input corresponds to an old output utxo from transaction [0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20fa0241106ee5a597c9](https://learnmeabitcoin.com/explorer/tx/0437cd7f8525ceed2324359c2d0ba26006d92d856a9c20fa0241106ee5a597c9).

So if you look at output 0 from that transaction that will represent the utxo_hint used to process the transaction.
![image](https://github.com/user-attachments/assets/d66f18ac-cde0-4f18-8143-9449232a8565)
