### ISSUE TITLE
[feat] Implement OP_WITHIN opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#19]
Implement the OP_WITHIN opcode using the opcodeWithin reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1844)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by supreme2580** [comment]
Hello @b-j-roberts could I work on this next after my current PR is reviewed and merged?

**Comment by b-j-roberts** [comment]
Yes, feel free to start now @supreme2580, you other pr looks good but I will review in detail soon
