### ISSUE TITLE
[feat] Max Stack size tests

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#191]
Create tests for features implemented in this issue : https://github.com/keep-starknet-strange/shinigami/issues/176

Push 1001 items onto the stack and ensure the script fails, push 1000 items and ensure the script doesn't fail.

**Comment by b-j-roberts** [comment]
@mubarak23 Here is that issue we discussed. Thanks

**Comment by mubarak23** [comment]
Yes, kindly assign @b-j-roberts

**Comment by b-j-roberts** [comment]
You can use `test_compile_and_run_with_err` to check for errors thrown from max stack elements reached 
https://github.com/keep-starknet-strange/shinigami/blob/ef7f31e4413114793b4b2892bd08e4e379409214/src/opcodes/tests/test_stack.cairo#L290
