### ISSUE TITLE
[feat] Compiler to optional

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#205]
Change the compiler from `opcodes: Felt252Dict<u8>` to `opcodes: Felt252Dict<Option<u8>>`, and [when compiling opcodes](https://github.com/keep-starknet-strange/shinigami/blob/688e464c6bb394608a37dcc1cf0a9f8db2ee9f5f/src/compiler.cairo#L367), throw an error if the opcode does not exist.

Create a set of test cases in `src/tests/test_compiler.cairo` of these new features.

#### References
[Compiler](https://github.com/keep-starknet-strange/shinigami/blob/main/src/compiler.cairo)

**Comment by stevencartavia** [comment]
Hi, I would like to try this one!

**Comment by mubarak23** [comment]
@b-j-roberts i have work on something like this before on this project, Kindly Assign

**Comment by ShantelPeters** [comment]
@b-j-roberts please can I be assigned to this issue

**Comment by JoE11-y** [comment]
Can I take a stab at this? @b-j-roberts.
