### ISSUE TITLE
[dev] [optimization] Division and modulus operations to div_rem

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#206]
To optimize shinigami, we should be using `div_rem` instead of `%` and `/` when doing these operations on the same number. So for each instance in the code where modulus and division are used together, we should change them to use div_rem instead to improve efficiency.

### References
[Div rem example](https://github.com/keep-starknet-strange/art-peace/blob/194197283e39607c92f2f6fb76b3cb7db58ddf4a/onchain/src/art_peace.cairo#L1104)
[Example of location to optimize in the code](https://github.com/keep-starknet-strange/shinigami/blob/688e464c6bb394608a37dcc1cf0a9f8db2ee9f5f/src/utils.cairo#L277)

**Comment by adrianvrj** [comment]
hi @b-j-roberts can I tackle this one?

**Comment by mubarak23** [comment]
@b-j-roberts optimizing the opcode is the best way to go, kindly assign

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts please can I work on this
