### ISSUE TITLE
[dev] [optimization] 'while i < n' to 'while x != n'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#207]
To optimize shinigami, we should be using `while x != n` instead of `while i < n` when doing loops over a range. So for each instance in the code where a `while i < n` type loop is used, if possible, we should change them to use `while x != n`.

### References
[Example of location to optimize in the code](https://github.com/keep-starknet-strange/shinigami/blob/688e464c6bb394608a37dcc1cf0a9f8db2ee9f5f/src/utils.cairo#L94)

**Comment by jsandinoDev** [comment]
Hi @b-j-roberts  can I work on this?

**Comment by raizo07** [comment]
@b-j-roberts can I work on this?

**Comment by Jemiiah** [comment]
@b-j-roberts  I would love to work on this

**Comment by Gift-Naomi** [comment]
@b-j-roberts can I work on this?

**Comment by ShantelPeters** [comment]
Hi @b-j-roberts can I take this up ?
