### ISSUE TITLE
[dev] [optimization] 'while i < data.len()' to 'let data_len = data.len()'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#208]
To optimize shinigami, we should be using `let data_len = data.len(); while i < data_len` instead of `while i < data.len()` when doing loops over a range. So for each instance in the code where a `while i < data.len()` type loop is used, if possible, we should change them to use `let data_len = data.len(); while i < data_len`.

### References
[Example of location to optimize in the code](https://github.com/keep-starknet-strange/shinigami/blob/688e464c6bb394608a37dcc1cf0a9f8db2ee9f5f/src/utils.cairo#L297)

**Comment by Iwueseiter** [comment]
Hi @b-j-roberts can I work on this?

**Comment by raizo07** [comment]
@b-j-roberts can I work on this

**Comment by Gift-Naomi** [comment]
@b-j-roberts can I work on this?

**Comment by ShantelPeters** [comment]
I will like to work on this

**Comment by b-j-roberts** [comment]
> @b-j-roberts can I work on this?

Yes, I will assign you and check back in a couple days. Please lmk if you have any questions

**Comment by b-j-roberts** [comment]
@Gift-Naomi Assigned 🚀
