### ISSUE TITLE
[bug] [bitcoin-core test] ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#211]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
```

This code should be passing, but is panicking when executing.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447137005097938746121282641147703],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
```

This comment might help some with how to debug : https://github.com/keep-starknet-strange/shinigami/pull/192#issuecomment-2322981566

**Comment by ShantelPeters** [comment]
@b-j-roberts can I work on this ?

**Comment by mubarak23** [comment]
If this is panicking the opcode is expecting a different value other than what was pass, a quick logs along the execution path will show what is happening, 

@b-j-roberts kindly assigned

**Comment by Jemiiah** [comment]
@b-j-roberts i would love to work on this issue ser

**Comment by b-j-roberts** [comment]
> @b-j-roberts can I please work on this ?

Yes, I can assign you. Thank you. Let me know if you have any questions, I will check-in in a couple days on progress.

**Comment by b-j-roberts** [comment]
@ShantelPeters Have you been able to get any progress debugging this yet?
