### ISSUE TITLE
[bug] [bitcoin-core test] ScriptSig: '0x27 0x302402107777777777777777777777777777777702108777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#212]
### Issue

The following bitcoin-core test is failing to give the correct result :
```
ScriptSig: '0x27 0x302402107777777777777777777777777777777702108777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT'
```

This code should be passing, but is panicking while executing.

### Replicate

To replicate the issue you can use the latest `main` branch with the following command:
```
scarb cairo-run '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447201069703897584165137845532471],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
```

This comment might help some with how to debug : https://github.com/keep-starknet-strange/shinigami/pull/192#issuecomment-2322981566

**Comment by od-hunter** [comment]
Can I do this please? @b-j-roberts

**Comment by mubarak23** [comment]
This bug is happening due to the way CHECKSIG OPCODE was  implemented 

A quick log along the execution path should show what is happening 

@b-j-roberts kindly assigned

**Comment by ScottyDavies** [comment]
@b-j-roberts can I hop on this?

**Comment by b-j-roberts** [comment]
> Can I do this please? @b-j-roberts

@od-hunter Sure, I will assign you. Let me know if you have questions and I will check-in in a couple days.

**Comment by b-j-roberts** [comment]
@od-hunter Hey, any luck working on this issue yet?
