### ISSUE TITLE
[feat] Implement OP_NEGATE opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#22]
Implement the OP_NEGATE opcode using the opcodeNegate reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1459)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by supreme2580** [comment]
Hi @b-j-roberts Can I be assigned to work on this?
