### ISSUE TITLE
[feat] Add support for OP_NOP2 & OP_NOP3 in compiler

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#228]
Add the following Opcodes to the compiler & opcodes list :
OP_NOP2 -> 0xb1 ( Same as Opcode::OP_CHECKLOCKTIMEVERIFY )
OP_NOP3 -> 0xb2 ( Same as Opcode::OP_CHECKSEQUENCEVERIFY )

#### References

[opcodes](https://github.com/keep-starknet-strange/shinigami/blob/13f6cf41c6ea1d3c229a2f10ce2ddb0a4626c6cc/packages/engine/src/opcodes/opcodes.cairo#L182)
[compiler](https://github.com/keep-starknet-strange/shinigami/blob/main/packages/compiler/src/compiler.cairo)

**Comment by adrianvrj** [comment]
@b-j-roberts can I work on this one?

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue ?

**Comment by Iwueseiter** [comment]
@b-j-roberts can I work on this?

**Comment by b-j-roberts** [comment]
> @b-j-roberts can I work on this one?

Sure, I'll assign you. Thanks
