### ISSUE TITLE
[feat] Add check_error_condition function to engine

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#229]
After a script executes with the Shinigami script engine, there are various checks that need to be made to ensure the script was successful.

BTCD implemented these inside a `CheckErrorCondition` function. We will need a similar function in our engine to ensure the Bitcoin transaction is valid.

#### Resources

- [btcd CheckErrorCondition](https://github.com/btcsuite/btcd/blob/67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54/txscript/engine.go#L876)
- [Shinigami engine](https://github.com/keep-starknet-strange/shinigami/blob/main/packages/engine/src/engine.cairo)

**Comment by Jemiiah** [comment]
I would love to take this issue @b-j-roberts

**Comment by Iwueseiter** [comment]
Hi @b-j-roberts can I work on this?

**Comment by manlikeHB** [comment]
@b-j-roberts, i would like to work on this.

**Comment by b-j-roberts** [comment]
I'll assign you @Jemiiah , please lmk asap if you have any questions!
