### ISSUE TITLE
[feat] Implement OP_ABS opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#23]
Implement the OP_ABS opcode using the opcodeAbs reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1473)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by b-j-roberts** [comment]
Definitely @princeibs ! Glad to have you on the project!
