### ISSUE TITLE
[dev] README badges cleanup

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#231]
In the README header, there are various badges like "Build: Passing", "Bitcoin", ...

I would like to include a couple new badges like : [Telegram chat](https://t.me/ShinigamiStarknet), [X badge](https://x.com/BitcoinWildlife), [cairo badge](https://github.com/keep-starknet-strange/raito/blob/main/README.md), ...

[Repo containing badges needed](https://github.com/Ileriayo/markdown-badges)

I think the best layout for the badges would be something like:

`Build: Passing`
`Bitcoin` `Cairo` `React`
`Exploration team` `telegram` `X`

**Comment by jsandinoDev** [comment]
Hi @b-j-roberts  can I work on this?

**Comment by Oshioke-Salaki** [comment]
Can

**Comment by Jemiiah** [comment]
I would love to work on this issue @b-j-roberts

**Comment by coxmars** [comment]
Hi @b-j-roberts, I would like to work on this issue asap 🫡

**Comment by raizo07** [comment]
Hello @b-j-roberts I'll like to be assigned to work on this

**Comment by b-j-roberts** [comment]
@jsandinoDev Definitely, let me know if you have any questions
