### ISSUE TITLE
[feat] Implement OP_NOT opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#24]
Implement the OP_NOT opcode using the opcodeNot reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1498)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by mubarak23** [comment]
@b-j-roberts kindly assign this issue to me

Thank you .

**Comment by b-j-roberts** [comment]
Glad to have you on this project @mubarak23 !
