### ISSUE TITLE
[feat] Implement P2SH tests / logic

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#243]
Bitcoin has many different transaction types, one of the more popular being P2SH.

In order to support these, we will need to make sure all edge cases and some mainnet P2SH transactions can successfully be validated by Shinigami.

Since Shinigami's design is heavily inspired by btcd, I recommend looking through all pay-to-script hash logic there and replicating it inside Shinigami's engine. Also, the learnmeabitcoin link can be super helpful in understanding Bitcoin P2SH transactions in depth.

Then, using the learnmeabitcoin P2SH examples and existing Shinigami transaction tests, create a set of tests to ensure all P2SH transactions run properly.

#### Resources

- [learnmeabitcoin P2SH](https://learnmeabitcoin.com/technical/script/p2sh/)
- [Existing P2PK & P2PKH tests in Shinigami](https://github.com/keep-starknet-strange/shinigami/tree/main/packages/engine/src/tests)
- [savedFirstStack btcd](https://github.com/btcsuite/btcd/blob/67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54/txscript/engine.go#L264)
- [bip16 flag btcd](https://github.com/btcsuite/btcd/blob/67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54/txscript/engine.go#L27)

**Comment by b-j-roberts** [comment]
@varun-doshi Here is the issue, please comment here

**Comment by varun-doshi** [comment]
Yup, I can take this up

**Comment by b-j-roberts** [comment]
Hey @varun-doshi , any updates on this issue?
Btw bip16 flags and support were added in [this PR](https://github.com/keep-starknet-strange/shinigami/pull/260), but we will still need the test cases from learnmeabitcoin

**Comment by varun-doshi** [comment]
> Hey @varun-doshi , any updates on this issue? Btw bip16 flags and support were added in [this PR](https://github.com/keep-starknet-strange/shinigami/pull/260), but we will still need the test cases from learnmeabitcoin

In progress
Should have an update soon

**Comment by b-j-roberts** [comment]
If we can get [this last test passing](https://github.com/keep-starknet-strange/shinigami/pull/268#pullrequestreview-2400549672), this issue will be complete !
Thanks for the efforts so far.

**Comment by varun-doshi** [comment]
I'll get on that
