### ISSUE TITLE
[bug] Remaining bitcoin-core test fixes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#247]
There are a lot of bitcoin-core tests that are still failing. I created this [file with all the failing tests](https://github.com/keep-starknet-strange/shinigami/blob/main/tests/script_tests_failing.json).

The file contains all the failing tests from [this file in bitcoin-core](https://github.com/bitcoin/bitcoin/blob/ab0b5706b254ed914f94b41940a946d84ac8dd6d/src/test/data/script_tests.json#L2).

I threw together [this bash script](https://github.com/keep-starknet-strange/shinigami/blob/main/tests/run-failing-core-tests.sh), which allows you to run all the failing tests.

It will go through them one by one, and print something like this for each failed test : 
```
  ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701' -- ScriptPubKey: '0 CHECKSIG NOT' -- Flags: '' -- Expected: OK
  Expected : OK -- Result   : PANIC
  FAIL
scarb cairo-run --package shinigami_cmds '[[85638222473728638769160410210893464261263086061422684165462972715402475319,97557673223841770041305211021412912560163447137005097938746121282641147703],5288612062596008609236648564283419927782315402045370417,23,[],976111785041138328458856412106580,14,[],0,0]'
     Running shinigami_cmds
Running Bitcoin Script with ScriptSig: '0x27 0x3024021077777777777777777777777777777777020a7777777777777777777777777777777701', ScriptPubKey: '0 CHECKSIG NOT' and Flags: ''
Run panicked with [1637570914057682275393755530660268060279989363 ('Index out of bounds'), ].
```

showing the script that executed, the expected result and the result. The following lines give the scarb command needed to run the failing test manually. Most of the tests have a small bit of info inside the `script_tests_failing.json` file that explains what it is trying to test, which is usually a good hint for where to look.

The task would be to go through these and fix them. Thank you!

Using btcd in general is very useful for seeing bitcoin spec/code to understand how things may differ in our implementation, since our design is heavily inspired by the work there. But in particular [this function will be super useful](https://github.com/btcsuite/btcd/blob/2b53ed198955ac40fe5b3ce4a854e9f5bfa68258/txscript/reference_test.go#L211) in seeing how they map errors to results from these bitcoin-core tests.

**Comment by b-j-roberts** [comment]
@bloomingpeach Could you comment here so I can mark you as working on this? Thank you!

**Comment by bloomingpeach** [comment]
@b-j-roberts can I work on this?

**Comment by SoarinSkySagar** [comment]
@b-j-roberts can i work on this?

**Comment by b-j-roberts** [comment]
For sure @SoarinSkySagar !

**Comment by SoarinSkySagar** [comment]
Hi @b-j-roberts, I think you closed this issue unknowingly because there are still some failing tests, which I'm currently working on.

**Comment by bloomingpeach** [comment]
> Hi @b-j-roberts, I think you closed this issue unknowingly because there are still some failing tests, which I'm currently working on.

@SoarinSkySagar because you are writing the PR description "resolves #xxx", which will auto close the issue when the PR is merged. Best practice should be "This PR addresses #..." if that PR doesn't fully resolve the issue.

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar because you are writing the PR description "resolves #xxx", which will auto close the issue when the PR is merged. Best practice should be "This PR addresses #..." if that PR doesn't fully resolve the issue.

I see, will remember that from next time 😅
but can this issue be opened again? I've fixed one more test
