### ISSUE TITLE
[feat] Implement P2MS tests / features

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#248]
Bitcoin has many different transaction types, one of them being P2MS.

In order to support these, we will need to make sure all edge cases and some mainnet P2MS transactions can successfully be validated by Shinigami.

The learnmeabitcoin link can be super helpful in understanding Bitcoin P2MS transactions in depth.

Then, using the learnmeabitcoin P2MS examples and existing Shinigami transaction tests, create a set of tests to ensure all P2MS transactions run properly.

Resources

[learnmeabitcoin P2MS](https://learnmeabitcoin.com/technical/script/p2ms/)
[Existing P2PK & P2PKH tests in Shinigami](https://github.com/keep-starknet-strange/shinigami/tree/main/packages/engine/src/tests)

**Comment by mubarak23** [comment]
I

**Comment by mubarak23** [comment]
@b-j-roberts am still available to work on this

**Comment by bloomingpeach** [comment]
@b-j-roberts May I work on this?

**Comment by manlikeHB** [comment]
Hi @b-j-roberts, can i work on this?
