### ISSUE TITLE
[feat] Implement P2WPKH tests/logic

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#249]
Bitcoin has many different transaction types, one of them being P2WPKH.

In order to support these, we will need to make sure all edge cases and some mainnet P2WPKH transactions can successfully be validated by Shinigami.

Since Shinigami's design is heavily inspired by btcd, I recommend looking through all the witness transaction logic there and replicating it inside Shinigami's engine, where needed. Many witness features are implemented, but notably witness signature calculation is not done in OP_CHECKSIG/OP_CHECKMULTISIG/... 
The learnmeabitcoin link can be super helpful in understanding Bitcoin P2WPKH transactions in depth.

Then, using the learnmeabitcoin P2WPKH examples and existing Shinigami transaction tests, create a set of tests to ensure all P2WPKH transactions run properly.

Resources

[learnmeabitcoin P2WPKH](https://learnmeabitcoin.com/technical/script/p2wpkh/)
[Existing P2PK & P2PKH tests in Shinigami](https://github.com/keep-starknet-strange/shinigami/tree/main/packages/engine/src/tests)
[witness sig btcd](https://github.com/btcsuite/btcd/blob/67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54/txscript/opcode.go#L2023)

**Comment by mubarak23** [comment]
I

**Comment by JoE11-y** [comment]
Hey @b-j-roberts.

Can I take a look at this?

**Comment by b-j-roberts** [comment]
@JoE11-y for sure, please lmk if you have questions! Good luck 🙏

**Comment by b-j-roberts** [comment]
Hey @JoE11-y , any updates on this issue? Many witness features have recently been merged, so I think the main thing we still need here is the P2WPKH tests from learnmeabitcoin.

**Comment by JoE11-y** [comment]
@b-j-roberts just added it now.
