### ISSUE TITLE
[feat] Implement P2WSH tests/logic

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#250]
Bitcoin has many different transaction types, one of them being P2WSH.

In order to support these, we will need to make sure all edge cases and some mainnet P2WSH transactions can successfully be validated by Shinigami.

Since Shinigami's design is heavily inspired by btcd, I recommend looking through all the witness transaction logic there and replicating it inside Shinigami's engine, where needed. Many witness features are implemented, but notably witness signature calculation is not done in OP_CHECKSIG/OP_CHECKMULTISIG/...
The learnmeabitcoin link can be super helpful in understanding Bitcoin P2WSH transactions in depth.

Then, using the learnmeabitcoin P2WSH examples and existing Shinigami transaction tests, create a set of tests to ensure all P2WSH transactions run properly.

Resources

[learnmeabitcoin P2WSH](https://learnmeabitcoin.com/technical/script/p2wsh/)
[Existing P2PK & P2PKH tests in Shinigami](https://github.com/keep-starknet-strange/shinigami/tree/main/packages/engine/src/tests)
[witness sig btcd](https://github.com/btcsuite/btcd/blob/67b8efd3ba53b60ff0eba5d79babe2c3d82f6c54/txscript/opcode.go#L2023)

**Comment by Kaminar-i** [comment]
**hello @b-j-roberts i would love to work on this issue :)**

**Comment by CollinsC1O** [comment]
Hello @b-j-roberts I'm a front-end and a blockchain developer. I will love to work on this

**Comment by manlikeHB** [comment]
Hi @b-j-roberts, can I work on this?

**Comment by augustin-v** [comment]
Hello, I have experience contributing to Kakarot zkEVM and I would love to spend time on this issue

**Comment by ptisserand** [comment]
Hi @b-j-roberts can I work on this ?
