### ISSUE TITLE
[feat] Implement OP_RESERVED opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#4]
Implement the OP_RESERVED opcode using the `opcodeReserved` reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L774)

#### References
[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Jemiiah** [comment]
hello @b-j-roberts i would love to work on this issue 🚀
