### ISSUE TITLE
[feat] Implement OP_2, OP_3, ..., OP_16 opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#5]
Implement the OP_X opcodes using the `opcode_n` function like `OP_1` from `shinigami`

#### References
[opcode_n](https://github.com/keep-starknet-strange/shinigami/blob/d0b45e0192e11ab60a83b4a7ced6207aa875cafc/src/opcodes/opcodes.cairo#L166)
[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by hakymulla** [comment]
can i take this?

**Comment by ptisserand** [comment]
@b-j-roberts I need at least `OP_2` to test implementation of `OP_MIN` #17 
Is it ok if I add OP_{2..16} in the same PR ?

**Comment by b-j-roberts** [comment]
Thank ya'll for the rapid turn around on this issue! @ptisserand @hakymulla
