### ISSUE TITLE
[feat] Implement OP_SWAP & OP_2SWAP opcodes

### ISSUE THREAD

**Issue by varun-doshi** [keep-starknet-strange/shinigami#54]
Would like to work on `OP_SWAP` opcode.
Apologies for not waiting for an official issue to be raised for it.

**Comment by b-j-roberts** [comment]
No worries, sure. I can assign you to this. I'll add info soon

**Comment by b-j-roberts** [comment]
@varun-doshi 

Implement the OP_SWAP & OP_2SWAP opcodess using the opcodeSwap and opcode2Swap [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1368)

This will include implementing a version of [SwapN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L273) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by varun-doshi** [comment]
Got it
Thank you
