### ISSUE TITLE
[feat] Implement OP_IFDUP opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#57]
Implement the OP_IFDUP opcode using the opcodeIfDup [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1275)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by EjembiEmmanuel** [comment]
@b-j-roberts I'd love to work on this

**Comment by varun-doshi** [comment]
Hi @b-j-roberts  Can i work on this?

**Comment by b-j-roberts** [comment]
@EjembiEmmanuel Awesome, I'll assign this one to you!

@varun-doshi , thanks for the application and interest. I'll try and create another issue for you soon, since you were able to complete OP_SWAP opcodes so quickly! Thank you

**Comment by varun-doshi** [comment]
> @EjembiEmmanuel Awesome, I'll assign this one to you!
> 
> @varun-doshi , thanks for the application and interest. I'll try and create another issue for you soon, since you were able to complete OP_SWAP opcodes so quickly! Thank you

Looking forward to the next issue
