### ISSUE TITLE
[feat] Implement OP_NIP opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#58]
Implement the OP_NIP opcode using the opcodeNip [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1317)

This will include implementing a version of [NipN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L146) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Iwueseiter** [comment]
Hi
