### ISSUE TITLE
[feat] Implement OP_TUCK opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#59]
Implement the OP_TUCK opcode using the opcodeTuck [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1376) and the [Tuck stack function](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L184)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by kateberryd** [comment]
Hi
