### ISSUE TITLE
[feat] Implement OP_TRUE opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#6]
Implement the OP_TRUE opcode using the `opcode_n` function like `OP_1` from `shinigami`

#### References
[opcode_n](https://github.com/keep-starknet-strange/shinigami/blob/d0b45e0192e11ab60a83b4a7ced6207aa875cafc/src/opcodes/opcodes.cairo#L166)
[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by hakymulla** [comment]
can i take this one?

**Comment by b-j-roberts** [comment]
Thank you, @hakymulla , I am glad to have you on this project. Will review your PR asap
