### ISSUE TITLE
[feat] Implement OP_EQUAL opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#61]
Implement the OP_EQUAL opcode using the opcodeEqual [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1398)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by hakymulla** [comment]
can i take this?

**Comment by b-j-roberts** [comment]
Thank you for the quick turn around on the issue @hakymulla , I'll take a look at your PR soon!
