### ISSUE TITLE
[feat] Implement OP_BOOLAND opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#63]
Implement the OP_BOOLAND opcode using the opcodeBoolAnd [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1577)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by supreme2580** [comment]
Hi @b-j-roberts I would like to work on this

**Comment by b-j-roberts** [comment]
Thank you for the quick turn around @supreme2580 , will review soon.

**Comment by supreme2580** [comment]
@b-j-roberts My pleasure
