### ISSUE TITLE
[feat] Implement OP_BOOLOR opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#64]
Implement the OP_BOOLOR opcode using the opcodeBoolOr [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1604)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by mubarak23** [comment]
I

**Comment by estherbreath** [comment]
Hello @b-j-roberts , my name is Esther Breath.

I'm interested in working on implementing the OP_BOOLOR opcode (#64). I've reviewed the `opcodeBoolOr` reference from btcd and believe I can adapt it effectively for `shinigami`. My plan involves integrating this opcode within the existing opcode handling framework, ensuring compatibility and efficiency. I'll also prepare a comprehensive documentation. Looking forward to potentially contributing to this project!

**Comment by b-j-roberts** [comment]
@estherbreath welcome to the project! Thanks for writing about your background and interest. Would love to have you on the project.

I'll assign you to this one, let me know if you have questions!

**Comment by estherbreath** [comment]
Thanks
