### ISSUE TITLE
[feat] Implement OP_NUMEQUAL opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#65]
Implement the OP_NUMEQUAL opcode using the opcodeNumEqual [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1629)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Jemiiah** [comment]
i would love to work on this issue @b-j-roberts

**Comment by byteZorvin** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/shinigami).

### My background and how it can be leveraged
I have been writing cairo from last 1 year and have decent experience, and love following its progress

**Comment by b-j-roberts** [comment]
@byteZorvin Thanks for applying, glad to have you on the project! I'll assign this one to you. Let me know if you have any questions.

@Jemiiah I will keep you on my short list for a new issue after your other issue is merged. Thank you

**Comment by harsh-ps-2003** [comment]
I have made the PR! The issue can be closed!

**Comment by harsh-ps-2003** [comment]
I have made the PR, this issue can be closed now @onlydustapp

**Comment by harsh-ps-2003** [comment]
I have made the PR, the issue can be closed now!
