### ISSUE TITLE
[feat] Implement OP_DROP & OP_2DROP opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#67]
Implement the OP_DROP & OP_2DROP opcodes using the opcodeDrop & opcode2Drop [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1303)

This will include implementing a version of [DropN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L205) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

**Comment by prasincs** [comment]
I can take this

**Comment by b-j-roberts** [comment]
@prasincs for sure, good luck!
