### ISSUE TITLE
[feat] Implement OP_DUP, OP_2DUP, and OP_3DUP opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#68]
Implement the OP_DUP, OP_2DUP, and OP_3DUP opcodes using the opcodeDup, opcode2Dup, and opcode3Dup [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1310)

This will include implementing a version of [DupN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L225) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Gift-Naomi** [comment]
Can I work on this?

**Comment by Xavek** [comment]
@b-j-roberts Looks like @Gift-Naomi has demonstrated interest in issue #66  too. Therefore, can I take this?

**Comment by b-j-roberts** [comment]
@Xavek yes, I'll assign this to you and the other for @Gift-Naomi. This on is more complex too, so might be better for you since you have contributed already. Thank you!
