### ISSUE TITLE
[feat] Implement OP_OVER & OP_2OVER opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#69]
Implement the OP_OVER & OP_2OVER opcodes using the opcodeOver and opcode2Over [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1324)

This will include implementing a version of [OverN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L297) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

**Comment by okhaimie-dev** [comment]
@supreme2580 you should do this one.

will work with you if you need any help

**Comment by okhaimie-dev** [comment]
@TEMHITHORPHE you can handle this

**Comment by b-j-roberts** [comment]
For sure @TEMHITHORPHE , glad to have new contributors on the project. I'll assign this to you.
@okhaimie-dev thank you for sharing the issue!

**Comment by b-j-roberts** [comment]
Hey @TEMHITHORPHE , any update here? I will go ahead and open this issue for others, but feel free to submit a PR with your work if you have something.

**Comment by mubarak23** [comment]
@b-j-roberts kindly assign this to me

**Comment by b-j-roberts** [comment]
Thanks @mubarak23 , I'll assign you.
