### ISSUE TITLE
[feat] Implement OP_NOP opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#7]
Implement the OP_NOP opcode using the opcodeNop reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L820)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by ptisserand** [comment]
Hi @b-j-roberts can I work on this one ?

**Comment by b-j-roberts** [comment]
@ptisserand feel free to start this after the OP_MIN if you finish
