### ISSUE TITLE
[feat] Implement OP_ROT & OP_2ROT opcodes

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#70]
Implement the OP_ROT & OP_2ROT opcodess using the opcodeRot and opcode2Rot [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1361)

This will include implementing a version of [RotN from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/stack.go#L248) on the [Shinigami stack object](https://github.com/keep-starknet-strange/shinigami/blob/main/src/stack.cairo).

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by b-j-roberts** [comment]
Fast turn around! I like it! I'll take a look at your draft soon @okhaimie-dev 🔥

**Comment by okhaimie-dev** [comment]
@b-j-roberts it is not ready yet. But yes, feel free to take a look

**Comment by okhaimie-dev** [comment]
@b-j-roberts I will get back to this in two days = I should be able to have a passing test by then. I have been traveling since yesterday, and also prepping for an interview
