### ISSUE TITLE
[feat] Implement OP_PICK opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#72]
Implement the OP_PICK opcode using the opcodePick [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1334)

#### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Oshioke-Salaki** [comment]
Ban

**Comment by Shoetan** [comment]
Hi @b-j-roberts  returning contributor. Any chance I get this one

**Comment by b-j-roberts** [comment]
@Oshioke-Salaki glad to have you on the project. LMK if you have questions!
