### ISSUE TITLE
[feat] Implement OP_TOALTSTACK opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#8]
Implement the OP_TOALTSTACK opcode using the opcodeToAltStack‎ reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1203)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by vibenedict** [comment]
Hi, i will like to work on this

**Comment by b-j-roberts** [comment]
Welcome to the project @vibenedict , let me know if you have questions or issues! Thank you

**Comment by b-j-roberts** [comment]
Hey, have you been able to start this @vibenedict ? This is blocking another issue ATM

**Comment by harsh-ps-2003** [comment]
I have made the PR, the issue can be closed now!
