### ISSUE TITLE
[feat] Implement OP_FROMALTSTACK opcode

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/shinigami#9]
Implement the OP_FROMALTSTACK opcode using the opcodeFromAltStack reference implementation from [btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L1218)

References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by Xavek** [comment]
I would like to take this. The approach is lean check the btcd impl in go and port in Cairo according to the guide provided

**Comment by b-j-roberts** [comment]
Awesome! Welcome to the project, let me know if you have any questions or issues. 🍎
