### ISSUE TITLE
[feat] Implement OP_RESERVED1 and OP_RESERVED2 opcode

### ISSUE THREAD

**Issue by mubarak23** [keep-starknet-strange/shinigami#91]
Implement the OP_RESERVED1 & OP_RESERVED2 following the [reference implementation from btcd](https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/txscript/opcode.go#L179)
### References

[Guide on how to add an opcode in shinigami](https://github.com/keep-starknet-strange/shinigami/blob/main/resources/how-to-add-an-opcode.md)

**Comment by mubarak23** [comment]
@b-j-roberts here is the issue, kindly assign

**Comment by b-j-roberts** [comment]
I think you can do `OP_VER` as well since it is another reserved opcode.

**Comment by mubarak23** [comment]
> If you'd like, you can do `OP_VER` together with these, since it is another reserved opcode

i will add it
